// Supported UI languages. `en.json` is the source of truth; the others are generated by scripts/translate-i18n.mjs.
export const LANGUAGES = [
  { code: "en", label: "English", dir: "ltr" },
  { code: "es", label: "Español", dir: "ltr" },
  { code: "fr", label: "Français", dir: "ltr" },
  { code: "de", label: "Deutsch", dir: "ltr" },
  { code: "pt", label: "Português", dir: "ltr" },
  { code: "zh", label: "中文", dir: "ltr" },
  { code: "ko", label: "한국어", dir: "ltr" },
  { code: "hi", label: "हिन्दी", dir: "ltr" },
  { code: "ar", label: "العربية", dir: "rtl" },
] as const;

export type Lang = (typeof LANGUAGES)[number]["code"];

export const isLang = (v: unknown): v is Lang => LANGUAGES.some((l) => l.code === v);
export const dirOf = (lang: Lang) => LANGUAGES.find((l) => l.code === lang)?.dir ?? "ltr";
