// GENERATED by scripts/sync-shared.sh from data/atlanta-activities.json. Do not edit by hand.
export const CATALOG_FILE = {
  "note": "DEMO DATA. Prices are APPROXIMATE per-person estimates in USD cents (tickets/meals change often and may be dynamic) and hours are typical, not guaranteed. Verify on each venue's site before relying on them. Nothing here is an endorsement or a booking.",
  "version": "2026-09-26",
  "city": "Atlanta, GA",
  "currency": "usd",
  "activities": [
    {
      "id": "ponce-city-market-food-hall",
      "name": "Ponce City Market Food Hall",
      "category": "food",
      "neighborhood": "Old Fourth Ward",
      "price_per_person_cents": 2000,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Daily ~11:00-21:00 (stalls vary)",
      "duration_minutes": 75,
      "transit_note": "On the BeltLine Eastside Trail; MARTA bus 2/102 nearby",
      "tags": [
        "food-hall",
        "variety",
        "indoor"
      ]
    },
    {
      "id": "skyline-park-pcm",
      "name": "Skyline Park (Ponce City Market rooftop)",
      "category": "activity",
      "neighborhood": "Old Fourth Ward",
      "price_per_person_cents": 2200,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Afternoons-evenings, later on weekends (seasonal)",
      "duration_minutes": 90,
      "transit_note": "Same building as the PCM food hall",
      "tags": [
        "rooftop",
        "games",
        "views"
      ]
    },
    {
      "id": "beltline-eastside-trail",
      "name": "Atlanta BeltLine Eastside Trail walk",
      "category": "outdoors",
      "neighborhood": "Inman Park / Old Fourth Ward",
      "price_per_person_cents": 0,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Daily, daylight recommended",
      "duration_minutes": 60,
      "transit_note": "Walkable from Inman Park/Reynoldstown MARTA",
      "tags": [
        "free",
        "walk",
        "street-art"
      ]
    },
    {
      "id": "krog-street-market",
      "name": "Krog Street Market",
      "category": "food",
      "neighborhood": "Inman Park",
      "price_per_person_cents": 1800,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Daily ~11:00-21:00 (stalls vary)",
      "duration_minutes": 60,
      "transit_note": "~15 min walk from Inman Park/Reynoldstown MARTA; on the BeltLine",
      "tags": [
        "food-hall",
        "variety",
        "indoor"
      ]
    },
    {
      "id": "georgia-aquarium",
      "name": "Georgia Aquarium",
      "category": "attraction",
      "neighborhood": "Downtown",
      "price_per_person_cents": 5000,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Daily ~10:00-20:00 (timed entry)",
      "duration_minutes": 150,
      "transit_note": "Walk from Peachtree Center or Civic Center MARTA",
      "tags": [
        "indoor",
        "iconic"
      ]
    },
    {
      "id": "world-of-coca-cola",
      "name": "World of Coca-Cola",
      "category": "attraction",
      "neighborhood": "Downtown",
      "price_per_person_cents": 2400,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Daily ~10:00-17:00 (extended in summer)",
      "duration_minutes": 105,
      "transit_note": "Pemberton Place, next to the Aquarium",
      "tags": [
        "indoor",
        "iconic",
        "tasting"
      ]
    },
    {
      "id": "center-civil-human-rights",
      "name": "National Center for Civil and Human Rights",
      "category": "museum",
      "neighborhood": "Downtown",
      "price_per_person_cents": 2200,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Wed-Mon ~10:00-17:00",
      "duration_minutes": 120,
      "transit_note": "Pemberton Place, walk from Peachtree Center MARTA",
      "tags": [
        "indoor",
        "history",
        "meaningful"
      ]
    },
    {
      "id": "mlk-national-historical-park",
      "name": "Martin Luther King Jr. National Historical Park",
      "category": "museum",
      "neighborhood": "Sweet Auburn",
      "price_per_person_cents": 0,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Daily ~9:00-17:00 (some buildings vary)",
      "duration_minutes": 90,
      "transit_note": "Atlanta Streetcar King Historic District stop",
      "tags": [
        "free",
        "history",
        "meaningful"
      ]
    },
    {
      "id": "sweet-auburn-curb-market",
      "name": "Sweet Auburn Curb Market",
      "category": "food",
      "neighborhood": "Sweet Auburn",
      "price_per_person_cents": 1500,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Mon-Sat ~8:00-18:00",
      "duration_minutes": 45,
      "transit_note": "Atlanta Streetcar Sweet Auburn Market stop",
      "tags": [
        "food-hall",
        "budget",
        "local"
      ]
    },
    {
      "id": "high-museum-of-art",
      "name": "High Museum of Art",
      "category": "museum",
      "neighborhood": "Midtown",
      "price_per_person_cents": 1900,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Tue-Sun ~10:00-17:00 (Sun from 12:00)",
      "duration_minutes": 120,
      "transit_note": "Next to Arts Center MARTA",
      "tags": [
        "indoor",
        "art"
      ]
    },
    {
      "id": "atlanta-botanical-garden",
      "name": "Atlanta Botanical Garden",
      "category": "outdoors",
      "neighborhood": "Midtown",
      "price_per_person_cents": 3000,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Tue-Sun ~9:00-17:00 (seasonal evening events)",
      "duration_minutes": 120,
      "transit_note": "~15 min walk from Arts Center MARTA",
      "tags": [
        "outdoors",
        "gardens"
      ]
    },
    {
      "id": "piedmont-park",
      "name": "Piedmont Park picnic",
      "category": "outdoors",
      "neighborhood": "Midtown",
      "price_per_person_cents": 0,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Daily 6:00-23:00",
      "duration_minutes": 90,
      "transit_note": "Walk from Midtown or Arts Center MARTA",
      "tags": [
        "free",
        "outdoors",
        "picnic"
      ]
    },
    {
      "id": "mary-macs-tea-room",
      "name": "Mary Mac's Tea Room",
      "category": "food",
      "neighborhood": "Midtown",
      "price_per_person_cents": 2800,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Daily ~11:00-21:00",
      "duration_minutes": 75,
      "transit_note": "Walk from North Avenue MARTA",
      "tags": [
        "southern",
        "classic"
      ],
      "dietary_note": "Vegetable-sides plate available"
    },
    {
      "id": "topgolf-midtown",
      "name": "Topgolf Midtown",
      "category": "activity",
      "neighborhood": "Midtown / West Midtown",
      "price_per_person_cents": 3500,
      "veg_friendly": true,
      "transit_friendly": false,
      "typical_hours": "Daily ~10:00-23:00 (later on weekends)",
      "duration_minutes": 120,
      "transit_note": "Best by car/rideshare",
      "tags": [
        "games",
        "group",
        "indoor-outdoor"
      ],
      "dietary_note": "Price is a bay-time share estimate, food extra"
    },
    {
      "id": "fox-bros-bbq",
      "name": "Fox Bros. Bar-B-Q",
      "category": "food",
      "neighborhood": "Candler Park",
      "price_per_person_cents": 2800,
      "veg_friendly": false,
      "transit_friendly": false,
      "typical_hours": "Daily ~11:00-22:00",
      "duration_minutes": 75,
      "transit_note": "Best by car/rideshare",
      "tags": [
        "bbq",
        "texas-style"
      ]
    },
    {
      "id": "busy-bee-cafe",
      "name": "Busy Bee Cafe",
      "category": "food",
      "neighborhood": "Vine City",
      "price_per_person_cents": 2200,
      "veg_friendly": false,
      "transit_friendly": true,
      "typical_hours": "Mon-Sat ~11:00-19:00, Sun ~12:00-19:00",
      "duration_minutes": 60,
      "transit_note": "Walk from Vine City MARTA",
      "tags": [
        "soul-food",
        "iconic"
      ]
    },
    {
      "id": "tassilis-raw-reality",
      "name": "Tassili's Raw Reality Cafe",
      "category": "food",
      "neighborhood": "West End",
      "price_per_person_cents": 1800,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Tue-Sun ~11:00-20:00",
      "duration_minutes": 60,
      "transit_note": "Walk from West End MARTA",
      "tags": [
        "vegan",
        "local"
      ]
    },
    {
      "id": "buford-highway-food-crawl",
      "name": "Buford Highway food crawl (2-3 stops)",
      "category": "food",
      "neighborhood": "Brookhaven / Chamblee / Doraville",
      "price_per_person_cents": 1800,
      "veg_friendly": true,
      "transit_friendly": false,
      "typical_hours": "Most spots ~11:00-22:00",
      "duration_minutes": 120,
      "transit_note": "Best by car/rideshare; MARTA bus 39 runs the corridor",
      "tags": [
        "international",
        "budget",
        "adventurous"
      ]
    },
    {
      "id": "plaza-theatre",
      "name": "Plaza Theatre movie",
      "category": "entertainment",
      "neighborhood": "Poncey-Highland",
      "price_per_person_cents": 1400,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Showtimes afternoons-late night",
      "duration_minutes": 150,
      "transit_note": "MARTA bus on Ponce de Leon Ave",
      "tags": [
        "indoor",
        "indie-film"
      ]
    },
    {
      "id": "dads-garage-improv",
      "name": "Dad's Garage improv show",
      "category": "entertainment",
      "neighborhood": "Old Fourth Ward",
      "price_per_person_cents": 2500,
      "veg_friendly": true,
      "transit_friendly": true,
      "typical_hours": "Shows Thu-Sat evenings",
      "duration_minutes": 105,
      "transit_note": "Walk/bike from the BeltLine or Inman Park MARTA",
      "tags": [
        "comedy",
        "indoor",
        "evening"
      ]
    },
    {
      "id": "fernbank-museum",
      "name": "Fernbank Museum",
      "category": "museum",
      "neighborhood": "Druid Hills",
      "price_per_person_cents": 2600,
      "veg_friendly": true,
      "transit_friendly": false,
      "typical_hours": "Daily ~10:00-17:00",
      "duration_minutes": 150,
      "transit_note": "Best by car; limited bus access",
      "tags": [
        "indoor",
        "science",
        "dinosaurs"
      ]
    },
    {
      "id": "atlanta-history-center",
      "name": "Atlanta History Center",
      "category": "museum",
      "neighborhood": "Buckhead",
      "price_per_person_cents": 2500,
      "veg_friendly": true,
      "transit_friendly": false,
      "typical_hours": "Tue-Sun ~10:00-17:30",
      "duration_minutes": 150,
      "transit_note": "Best by car; ~20 min walk from Buckhead-area bus stops",
      "tags": [
        "indoor",
        "history",
        "gardens"
      ]
    },
    {
      "id": "chattahoochee-river-hike",
      "name": "Chattahoochee River NRA hike (Cochran Shoals)",
      "category": "outdoors",
      "neighborhood": "Sandy Springs / Marietta",
      "price_per_person_cents": 0,
      "veg_friendly": true,
      "transit_friendly": false,
      "typical_hours": "Daily dawn-dusk",
      "duration_minutes": 120,
      "transit_note": "Car needed; ~$5/vehicle parking fee not included",
      "tags": [
        "free",
        "outdoors",
        "nature"
      ]
    },
    {
      "id": "stone-mountain-summit-hike",
      "name": "Stone Mountain summit hike",
      "category": "outdoors",
      "neighborhood": "Stone Mountain",
      "price_per_person_cents": 500,
      "veg_friendly": true,
      "transit_friendly": false,
      "typical_hours": "Daily ~5:00-24:00 (park grounds)",
      "duration_minutes": 150,
      "transit_note": "Car needed; price = ~$20/vehicle parking split ~4 ways",
      "tags": [
        "outdoors",
        "hike",
        "views"
      ]
    }
  ]
} as const;
