#!/usr/bin/env bash
# Edge Functions can only bundle files under supabase/functions/. This script generates TS modules
# in supabase/functions/_shared/ from the canonical files, which avoids JSON import attributes at deploy time:
#   data/atlanta-activities.json -> _shared/catalog.ts
#   schema/plan.schema.json      -> _shared/plan-schema.ts
#   prompts/make-plan.md         -> _shared/system-prompt.ts   (text between PROMPT:START/END)
# Re-run after editing any of the three canonical files.
set -euo pipefail
cd "$(dirname "$0")/.."
node -e '
const fs = require("fs");
const out = "supabase/functions/_shared/";
const hdr = (src) => `// GENERATED by scripts/sync-shared.sh from ${src}. Do not edit by hand.\n`;
const catalog = JSON.parse(fs.readFileSync("data/atlanta-activities.json", "utf8"));
fs.writeFileSync(out + "catalog.ts", hdr("data/atlanta-activities.json") +
  "export const CATALOG_FILE = " + JSON.stringify(catalog, null, 2) + " as const;\n");
const schema = JSON.parse(fs.readFileSync("schema/plan.schema.json", "utf8"));
fs.writeFileSync(out + "plan-schema.ts", hdr("schema/plan.schema.json") +
  "export const PLAN_SCHEMA: Record<string, unknown> = " + JSON.stringify(schema, null, 2) + ";\n");
const md = fs.readFileSync("prompts/make-plan.md", "utf8");
const m = md.match(/<!-- PROMPT:START -->\n([\s\S]*?)\n<!-- PROMPT:END -->/);
if (!m) { console.error("prompt markers not found in prompts/make-plan.md"); process.exit(1); }
fs.writeFileSync(out + "system-prompt.ts", hdr("prompts/make-plan.md") +
  "export const SYSTEM_PROMPT = " + JSON.stringify(m[1]) + ";\n");
'
echo "synced data/, schema/, prompts/ -> supabase/functions/_shared/{catalog,plan-schema,system-prompt}.ts"
